# Producer: Dmitriy Efremov <d.efremov@zarplata.ru>
# Maintainer: Andrey Kitsul <a.kitsul@zarplata.ru>
# Contributor: Andrey Platonov <a.platonov@zarplata.ru>

pkgname=zabbix-agent-extension-elasticsearch
pkgver=${PKGVER:-autogenerated}
pkgrel=${PKGREL:-1}
pkgdesc='Extension for zabbix-agentd for monitoring Elasticsearch service'

arch=('x86_64')
license=('GPL')

makedepends=('go')
depends=('zabbix-agent')
install='install.sh'

_branch=${BRANCH:-master}
source=("git+https://github.com/zarplata/${pkgname}.git#branch=${_branch}")

sha256sums=('SKIP')

pkgver() {
    cd "$srcdir/$pkgname"
    make version
}

build() {
    cd "$srcdir/$pkgname"
    make
}

package() {
    cd "$srcdir/$pkgname"
    make PREFIX=$pkgdir install
}
