# Maintainer: Andrey Kitsul <a.kitsul@zarplata.ru>
# Contributor: Andrey Platonov <a.platonov@zarplata.ru>

pkgname=zabbix-agent-extension-elasticsearch
pkgver=${PKGVER:-autogenerated}
pkgrel=${PKGREL:-1}
_branch=${BRANCH:-master}
pkgdesc="Extension for zabbix-agentd for monitoring Elasticsearch service"
arch=('any')
license=('GPL')
makedepends=('go' 'git' 'dep')
depends=('zabbix-agent')
install="install.sh"
source=("git+https://github.com/zarplata/$pkgname.git#branch=$_branch")
md5sums=(
    'SKIP'
    )

build() {
    cd "$srcdir/$pkgname"

    rm -rf "$srcdir/.go/src"
    mkdir -p "$srcdir/.go/src/git.rn/zp"

    export GOPATH="$srcdir/.go"

    mv "$srcdir/$pkgname" "$srcdir/.go/src/git.rn/zp"
    cd "$srcdir/.go/src/git.rn/zp/$pkgname"

    make
}

package() {
    cd "$srcdir/.go/src/git.rn/zp/$pkgname"

    ZBX_INC_DIR=/etc/zabbix/zabbix_agentd.conf.d/

    install -Dm 0755 .out/"${pkgname}" "${pkgdir}/usr/bin/${pkgname}"
    install -Dm 0644 "${pkgname}.conf" "${pkgdir}${ZBX_INC_DIR}${pkgname}.conf"
    
}
